name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  calendar_view:
    path: ../
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  groq: ^1.0.0
  sqflite: ^2.3.0
  path: ^1.8.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints:
  build_runner: ^2.0.6
  build_web_compilers: ^3.0.0

flutter:
  uses-material-design: true
