name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  calendar_view: ^1.4.0
  flutter_dotenv: ^5.2.1
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  chat_gpt_sdk: ^3.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6

flutter:
  uses-material-design: true

